---
title: "Invited Public Engagement"
slug: public
sidebar: false
toc: false
---

As an applied researcher, much of my work focuses on communicating findings from research to donors, policymakers, and civil society groups. Occasionally, I also receive invitations to advise these organizations on strategy and governance. 

### Amnesty International Advisory Panel for the Governance of Human Rights Organizations

I was invited to co-author the [Report of the Advisory Panel on the Governance of Human Rights Organizations](https://doi.org/10.31235/osf.io/7devb). Convened by Dr. Hazar Yueksel, Candidate Member of the Board of Directors at Amnesty International, this report synthesizes insights from social science research and legal studies to advise Amnesty International and other large, non-profit organizations on ethical issues related to non-profit governance. 


### Interview for the Ethical AI Manifesto

An interview with MLP’s Jeremy Springman (Director of Civic Research) was featured in the [Civil Society Manifesto for Ethical AI](https://www.forus-international.org/en/pdf-detail/106205-civil-society-manifesto-for-ethical-ai) , published by Foris International. The manifesto aims to give voice to a diverse group of civic actors working on subjects that are being affected by ongoing advances in AI. The interview focuses on how MLP uses machine learning to provide digital tools designed to help civil society.


### World Bank EngageFest webinar

The Machine Learning for Peace (MLP) was featured in the World Bank's EngageFest webinar a using AI analytics for citizen engagement. Watch the recording to learn about three case studies of projects using AI/ML for civic engagement and to hear a panel discussion of these issues

{{< video https://vimeo.com/885720507 >}}



### Evidence for Impact Webinar Series

The Machine Learning for Peace (MLP) was featured in the Promise and Perils of Data Science for Development webinar as part of the [Social Impact Evidence for Impact Webinar Series](https://socialimpact.com/evidence-for-impact-webinar-series/). The webinar discussed how data science can be used to improve development effectiveness. The presentation concluded with critical reflections from within USAID on the promise and pitfalls of using data science for development.

{{< video https://www.youtube.com/watch?v=INREs1yW2Zc&t=1s >}}


### Panel discussion at the Paris Peace Forum

The Machine Learning for Peace (MLP) project was one of 60 projects hosted at the 2022 [Paris Peace Forum](https://parispeaceforum.org/en/projects/machine-learning-for-peace/) in November. Below is a video of the panel discussion during the Forum’s AI in International Development roundtable discussion.

{{< video https://www.youtube.com/watch?v=8yaz4zK5Gqk&t=1s >}}


### 3ie Civil Society Evidence Gap Maps Advisory Group Member & 2023

In 2023, I was a member of the [Adivisory Group](https://3ieimpact.org/sites/default/files/2023-03/Civil-society-Online-appendix-D.pdf) for the [3ie Civil Society Evidence](https://www.3ieimpact.org/evidence-hub/publications/evidence-gap-maps/strengthening-civil-society-evidence-gap-map).
