\documentclass[11pt]{article} 

\usepackage{helvet}
\usepackage[hidelinks]{hyperref}
\usepackage{csquotes}
\usepackage{subcaption}
\usepackage[left=.7in,
            right=.7in,
            top=.7in,
            bottom=.5in,]{geometry}
\addtolength{\topmargin}{0in}
\pagenumbering{arabic}
\usepackage{ragged2e}
\usepackage{parskip}
\setlength{\parindent}{0pt}
\usepackage[font=small,skip=2pt]{caption}
\usepackage{multicol}
\setlength{\multicolsep}{6.0pt plus 2.0pt minus 1.5pt}% 50% of original values
\usepackage{hyperref}
\usepackage{fontspec}
\usepackage{fontawesome}
\usepackage[misc]{ifsym}
\usepackage{enumitem}
\usepackage[compact]{titlesec}
\usepackage{longtable}
\usepackage{academicons}
\usepackage{datetime}
\renewcommand{\today}{\monthname[\the\month] \the\year}

\begin{document}
\thispagestyle{empty}
\SweaveOpts{concordance=TRUE}


\begin{multicols}{2}
{\Large {\bf Jeremy Springman, PhD}}\\
Research Assistant Professor\\
University of Pennsylvania\\
%Updated \today \\

\columnbreak
\begin{flushright}

\faEnvelope: \href{mailto:jspr@sas.upenn.edu}{jspr@sas.upenn.edu}\\
\faLaptop: \url{jrspringman.github.io}\\
\faGithub: \url{https://github.com/jrspringman}\\
%\aiGoogleScholar:  \url{https://shorturl.at/ixTW8}\\
\end{flushright}
\end{multicols}
%\rule[0.9\baselineskip]{\textwidth}{.5pt}
\vspace{-10pt}

Applied researcher working to design, implement, and evaluate data-driven solutions to complex problems:
\begin{itemize}[itemsep=0mm, parsep=0pt]
\item 6 years experience recruiting and managing interdisciplinary team of 12 data science researchers
\item 10 years experience with causal inference and machine learning research design and execution
\item Passionate about communicating research for non-technical audiences to inform decision-making
\end{itemize}

\textbf{\large Work Experience}\\
\rule[3mm]{\textwidth}{.2pt}
\noindent\begin{tabular*}{\textwidth}{@{}l@{\extracolsep{\fill}}r@{}}
\textbf{\href{https://www.polisci.upenn.edu/}{University of Pennsylvania}, \href{https://web.sas.upenn.edu/dev-lab/}{PDRI-DevLab}}\\
Research Assistant Professor & July 2024 -- Present\\
Senior Research Associate \& Director of Research & July 2022 -- June 2024\\
\end{tabular*}
\begin{itemize}[itemsep=0mm, parsep=0pt]
\item Awarded \$3.5 million in federal and private research grants as a principal investigator 
\item Deployed public-facing \textbf{R Shiny} data dashboards and early warning system to inform crisis response and policy planning (150 hours of monthly usage; 800 policymakers signed-up for newsletter)
\item Designed and analyzed randomized experiments to measure success and efficiency of client projects
%\item Prepared 6 manuscripts for submission to academic journals
\item Developed course and mentored students on causal inference + research tools (\textbf{R}, \textbf{Quarto}, \textbf{GitHub})
\end{itemize}
%ML/AI to extract information from highly-multilingual text for a continuous, large-scale data production operation
%Manage projects from conceptualization and proposal through design, implementation, and the dissemination of results to the scientific and policy communities.

\noindent\begin{tabular*}{\textwidth}{@{}l@{\extracolsep{\fill}}r@{}}
\textbf{\href{https://polisci.duke.edu/}{Duke University}, \href{https://www.devlabduke.com/}{DevLab@Duke}}\\
Senior Research Associate & July 2021 -- June 2022\\
Post-Doctoral Research Associate & January 2019 -- June 2021\\
\end{tabular*}
\begin{itemize}[itemsep=0mm, parsep=0pt]
\item Led development of large-scale webscraping and highly-multilingual ML text classification pipeline (\textbf{Python} and \textbf{R}) to track and forecast political instability in 63 countries
\item Published 3 empirical research articles in peer-reviewed academic journals
\end{itemize}

% \textbf{\large Education}\\
% \rule[3mm]{\textwidth}{.2pt}
% \noindent\begin{tabular*}{\textwidth}{@{}l@{\extracolsep{\fill}}r@{}}
% \textbf{\href{https://www.sas.upenn.edu/polisci/}{University of Pennsylvania}}\\
% Ph.D. in Comparative Politics \& International Relations & 2019\\
% M.A. in Political Science & 2015\\
% \textbf{University of Pittsburgh}\\
% B.A. in Politics \& Philosophy (Honors College) & 2012
% \end{tabular*}

\textbf{\large Recent Invited Public Speaking}\\
\rule[3mm]{\textwidth}{.2pt}
\vspace{-25pt}
\begin{itemize} \itemsep -5pt
  \item U.S. Department of State (Washington, D.C.): Presented results from commissioned trial applying original data and time-series forecasting to guide budget and operations planning
  \item U.S. Army (\textit{Fort Liberty}); Leibniz Center for Informatics (\textit{Germany}); UN Data Strategy Community (\textit{remote}); Vienna University of Economics and Business (\textit{Austria}): Introduced public-facing data products to track political events and forecast instability in emerging markets
  \item Perry World House (Philadelphia): Discussed research to inform decision-makers' understanding of Russia's foreign influence operations in developing countries
\end{itemize}


\textbf{\large Selected Academic Manuscripts Under Review (contact for full list)}\\
\rule[3mm]{\textwidth}{.2pt}
\vspace{-25pt}
\begin{itemize} \itemsep -5pt
  \item Synthetic control analysis estimating effect of legal changes on dyadic aid flows (\textit{revise \& resubmit})
  \item RCT to expand youth social networks and civic engagement in Ethiopia + estimate network spillovers
  \item Conjoint survey experiment + bayesian regularization on organization decision-making in autocracies
  \item Original high-frequency data and evidence on strategic logic of Russia's foreign influence operations 
  \item Spatial difference-in-differences with ML weighting on geotagged aid projects and election outcomes
\end{itemize}

\textbf{\large Selected Policy Reports in 2024 (contact for full list)}\\
\rule[3mm]{\textwidth}{.2pt}\vspace{-5pt}
{\sl High Frequency Tracking of Civic Space Utilizing Domestic News Scraping and LLM Classification}\\
{\sl Forecasting High-Level Travel Advisories with Machine Learning for Peace Data}\\
- Prepared for Swift Expertise and Grounded Analytics Task Order by USAID DRG Bureau\\
{\sl Charting a Course for Applied Research in Peacebuilding}\\
- Published by United States Institute of Peace


% {\sl Report of the Advisory Panel for the Governance of Human Rights Organizations}\\
% Convened for Amnesty International by Dr. Hazar Yueksel (SocArXiv DOI: \href{https://doi.org/10.31235/osf.io/7devb}{10.31235})

% {\sl Ethical AI Manifesto (interview)}\\
% Published by Foris International
% {\sl Zimbabwe Governance Indicators Analysis}\\
% Prepared for USAID Zimbabwe\\



% \textbf{\large Teaching \& Advising}\\
% \rule[3mm]{\textwidth}{.2pt}
% \noindent\begin{tabular*}{\textwidth}{@{}l@{\extracolsep{\fill}}r@{}}
% 
% \textbf{University of Pennsylvania}: Professor\\
% \href{https://jrspringman.github.io/psci3200-globaldev/}{Global Development: Intermediate Topics in Politics, Policy, and Data} & Spring 2024, 2025\\
% Fels Institute of Government Lab Capstone Partner & Spring 2024
% \end{tabular*}
% 
% \textbf{Local Evaluation and Evidence Support (LEES)}: Academic Lead (ongoing)\\
% Data science and causal inference training for USAID local partners in Zambia and Ghana
% 
% 
% \textbf{\large References}\\
% \rule[3mm]{\textwidth}{.2pt}
% \begin{multicols}{2}
% \vspace{-20pt}
% Erik Wibbels\\
% Presidential Penn Compact Professor\\
% University of Pennsylvania\\
% ewibbels@sas.upenn.edu
% 
% Guy Grossman\\
% Knott Professor of Global Politics\\
% University of Pennsylvania\\
% ggros@sas.upenn.edu
% 
% 
% \end{multicols}

\end{document}
